DEBUG = 1
DEFAULT_SCALE = 1
DEFAULT_ALGORITHM = 1
DEFAULT_COLOR = '#FF0000' # Red
DEFAULT_PRIMARY_COLOR = '#000000' # Black
DEFAULT_SECONDARY_COLOR = '#FF0000' # Red
CANVAS_BG = "white"
GUI_BG = '#eeeeee'
CANVAS_WIDTH = 1280
CANVAS_HEIGHT = 720
MIN_RES = 1
MAX_RES = 64
MODOS = {"Edición" : 0, "Selección" : 1}
ALGORITMOS = {"Direct Scan Conversion" : 0, "Digital Differential Analyzer (DDA)" : 1, "Bresenham’s algorithm" : 2}
FRAMERATE = 60